### ISSUE TITLE
Supported Docbook Tag List @SUSE

### ISSUE THREAD

**Issue by jcayouette** [openSUSE/docbookrx#14]
:information_source: https://docs.google.com/spreadsheets/d/1STdjzI9n5BrNOPoCoMPoH2SwlXoyzWxACBLRFVbmxDU/edit?usp=sharing

**Comment by jcayouette** [comment]
:information_source:

**Comment by jcayouette** [comment]
:information_source:

**Comment by kkaempf** [comment]
This is handled in `testsuite` now. Run
> rake test

for full validation
