### ISSUE TITLE
Check if we can validate output against geekodoc relaxNG schema

### ISSUE THREAD

**Issue by jcayouette** [openSUSE/docbookrx#18]
Instead of writing and maintaining an xml document we should be able to test against the schema itself.

Using this library:
http://ruby-doc.org/stdlib-1.9.3/libdoc/rexml/rdoc/REXML/Validation/RelaxNG.html

And this schema:
https://github.com/openSUSE/geekodoc/blob/develop/geekodoc/rng/geekodoc5-flat.rnc

**Comment by kkaempf** [comment]
Use a a sledgehammer to crack a nut.
