### ISSUE TITLE
<simplepara> should just be <para>

### ISSUE THREAD

**Issue by jcayouette** [openSUSE/docbookrx#2]
At SUSE we are using para. We need to remove simplepara or just make para the default with simplepara being the secondary choice.

**Comment by kkaempf** [comment]
<simpara> seems to work nicely, where's the bug ?

**Comment by kkaempf** [comment]
@jcayouette ping

**Comment by kkaempf** [comment]
<simpara> is used everywhere within `asciidoctor` -> wontfix
