### ISSUE TITLE
Tags missing from testsuite

### ISSUE THREAD

**Issue by jcayouette** [openSUSE/docbookrx#22]
Add these final tags to test document, commented out so they can be enabled one at a time.
Many of these are just subtags/nodes to one element for example: (tbody, tgroup, tfoot, colspec, row etc.)

- [X] callout
- [X] calloutlist
- [X] citetitle
- [X] co
- [X] command
- [X] constant
- [X] date
- [X] email
- [X] emphasis
- [X] example
- [X] filename
- [X] formalpara
- [X] guimenu
- [X] index
- [X] indexentry
- [X] link
- [X] member
- [X] menuchoice
- [X] option
- [X] package
- [X] parameter
- [X] preface
- [X] primary
- [X] remark
- [X] replaceable
- [X] screen
- [X] secondary
- [X] see
- [X] simplelist
- [X] systemitem
- [X] tertiary
- [X] textobject (acts as alt text inside the mediaobject, placed in figure block)
- [X] table
- [X] informaltable
- [X] tbody
- [X] tfoot
- [X] tgroup
- [X] titleabbrev
- [X] trademark
- [X] uri
- [X] varname
- [ ] year
- [ ] task
- [ ] taskprerequisites
- [ ] taskrelated
- [ ] tasksummary
- [X] colspec
- [X] entry
- [ ] envar
- [ ] glossary
- [ ] glossdef
- [ ] glossdiv
- [ ] glossentry
- [ ] glossterm
- [ ] phrase
- [ ] quote
- [X] row
- [X] stepalternatives
- [X] substeps
- [ ] superscript

Def of done:
All tags are included in the docbookrx testsuite, commented out for Klaus to enable and test.

**Comment by kkaempf** [comment]
see #23
