### ISSUE TITLE
Make <section> optional and make <sect1 - 5> the default for sections.

### ISSUE THREAD

**Issue by jcayouette** [openSUSE/docbookrx#3]
At SUSE we use sect1 -5 to designate section depth. In docbook there are two choices. You can use section which can be infinitely nested and sect1 -5, the max being 5 sections deeps. We use sect for clarity and to limit nesting.

```xml
<sect1>
    <sect2>
        <sect3>
            <sect4>
               <sect5>
               </sect5>
            </sect4>
        </sect3>
    </sect2>
</sect1>
```

**Comment by kkaempf** [comment]
Doesn't matter
