### ISSUE TITLE
<command> tag is converted into useless output

### ISSUE THREAD

**Issue by r0ckarong** [openSUSE/docbookrx#32]
<command> is converted to [command]``text`` which isn't any valid element in Asciidoc. This should just be treated like `literal` and be converted to single backtick.

```
<command>ls -la</command>
```

```
`ls -la`
```

Inside <screen> this should not be converted at all and just output the text inside the tags.

**Comment by kkaempf** [comment]
Needs example. I believe that asciidoctor support this ?!

**Comment by r0ckarong** [comment]
Input:
https://github.com/SUSE/doc-caasp/blob/adoc/xml/admin_software.xml#L126

Output: 
https://github.com/SUSE/doc-caasp/blame/adoc/adoc/admin_software.adoc#L87

The double backticks should not be there.

The text formatting in code blocks does not work in the PDF output. Maybe we can ignore that part of the problem.

**Comment by r0ckarong** [comment]
So the only syntax highlighter that actually supports this in the PDF output is pygments but that also strips all the colors from the actual highlights making them less useful. 

In my opinion allowing formatting text in the code examples causes all kinds of follow-up problems like which substitutions to enable and unforseen substitutions with raw outputs etc.. I would make this a styleguide item to not use formatting inside code examples so we can use proper highlighting and avoid using different highlighters for the two outputs.
