### ISSUE TITLE
Support the <part> tag

### ISSUE THREAD

**Issue by jcayouette** [openSUSE/docbookrx#4]
We use the \<part> tag in books to designate book "parts"  E.g. Installation, Deployment, Migration etc.
Currently docbookRx does not recognize the \<part> tag. We need to add this functionality when its reading through a book.xml file.

https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/_includes/book-part.adoc

**Comment by kkaempf** [comment]
`testsuite/xml/book.xml` has `<part>` and it works nicely.
