### ISSUE TITLE
Add Appendix as a supported document type

### ISSUE THREAD

**Issue by jcayouette** [openSUSE/docbookrx#5]
Appendix is missing from the supported document types:
`/lib/docbookrx/docbook_visitor.rb`

This is required as some of SUSE's larger books have appendix documents and do not just use the tag internal to a document. The document itself is an appendix and is linked from a book entry.

```Ruby
DOCUMENT_NAMES = ['article', 'book']
```

**Comment by kkaempf** [comment]
it's a special section name.
