### ISSUE TITLE
Some tables are not read properly or not formatted correctly

### ISSUE THREAD

**Issue by jcayouette** [openSUSE/docbookrx#7]
To duplicate bug:
 Clone cloud documentaiton and convert bk_openstack_admin.xml and bk_openstack_user.xml
https://github.com/SUSE-Cloud/doc-cloud

2 columns specified in table '', but only 1 headers
11 columns specified in table '', but only 6 headers
10 columns specified in table '', but only 6 headers
11 columns specified in table '', but only 6 headers
11 columns specified in table '', but only 6 headers

**Comment by kkaempf** [comment]
This needs a minimal test case within `testsuite`

**Comment by kkaempf** [comment]
fixed with https://github.com/openSUSE/docbookrx/commit/1fb8cf39d93d75c734a8c981325f158c036109e9
