### ISSUE TITLE
Add support for Docbook <procedure>

### ISSUE THREAD

**Issue by jcayouette** [openSUSE/docbookrx#8]
### Adding Docbook Procedure Support
- [ ] How do procedures look once converted to asciidoc? We may need to improve this syntax, and check how  they are converted back to xml procedures for publishing.  see: 
1.) Extension: https://github.com/asciidoctor/asciidoctor-extensions-lab/tree/master/lib/steps-postprocessor
2.) Custom template: https://github.com/asciidoctor/asciidoctor-backends/blob/master/slim/docbook45/block_olist.xml.slim
3.) Community Proposal: https://github.com/asciidoctor/asciidoctor/issues/192#issuecomment-15321665

`procedure`
`title`A Title`/title`
`step`
`para`Step one`/para`
`/step`
`/procedure`

**Comment by kkaempf** [comment]
Hmm, `<procedure>` works for `testsuite/xml/chapter.xml`. Not sure what's missing.

Closing for now.
